AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sendgrid Inbound API to Discord

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  DiscordWebhookURL:
    Type: String
    Description: Discord Webhook URL for Notification

Resources:
  SendgridFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sendgrid/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        Sendgrid:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sendgrid
            Method: POST
      Environment:
        Variables:
          DiscordWebhookEnv: !Ref DiscordWebhookURL

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SendgridApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/sendgrid/"
  SendgridFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SendgridFunction.Arn
  SendgridFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SendgridFunctionRole.Arn
